### ISSUE TITLE
Coming across an error when at the Maven part

### ISSUE THREAD

**Issue by EvanET13** [IlluzionzDev/RainbowBot#7]
Upon running the `mvn clean install`, i get the following error:

```[ERROR] Failed to execute goal on project core: Could not resolve dependencies for project com.illuzionzstudios:core:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.illuzionzstudios:discord-library:jar:1.0: Failed to read artifact descriptor for com.illuzionzstudios:discord-library:jar:1.0: Could not transfer artifact com.illuzionzstudios:discord-library:pom:1.0 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [maven (http://_privateIP_/repository/maven-releases/, default, releases+snapshots)]```

**Comment by IlluzionzDev** [comment]
This needs to be fixed as the library doesn't exist. Will be fixed soon
